### ISSUE TITLE
Pull request?

### ISSUE THREAD

**Issue by MLDERES** [holdmydata/WMComplaintAnalyzer#1]
Offering to allow a pull request in an empty repository just another way of saying "Hey come do this idea for me!  I've got no idea where to start, so it would be great if you would just get it done."?  I'd be glad to give you something to pull in, but without even an inkling of how this project is meant to work or the goal of the project - it will be difficult to help...

... moving on...

**Comment by holdmydata** [comment]
LOL - I have no idea why I wrote any of that for a personal script. Thought someone in the vendor world might want to use it, but I haven't touched it in a while. I should go back in to all of these and adjust the readme to reflect more on the repos. Thanks for letting me know! Will work on documenting these better. Thank you!

**Comment by holdmydata** [comment]
Adjusted Readme a little but will add more when possible. Currently just the complaintNLP.py file is all that is used here, so will remove the vscode folder as well. Thank you for keeping me on my toes!
